name: Deploy Frontend

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Deploy to Nginx root
        run: |
          sudo rm -rf /var/www/hrfms-frontend/*
          sudo cp -r dist/* /var/www/hrfms-frontend/
          sudo nginx -t
          sudo systemctl reload nginx
